### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by ekupris** [sweIhm-ws2018-19/skillproject-di-1#1]
bitte Aufgabe 4 aus SWE1 Praktikum implementieren

**Comment by eulersexception** [comment]
bitte Java-Code aus Aufgabe 4 reviewen @ekupris @suglio

**Comment by eulersexception** [comment]
Der Vollständigkeit halber ist noch anzumerken, dass wir uns strikt an die Aufgabenstellung gehalten haben und keine zusätzliche Klassen "GeldBetrag" geschrieben haben und auch die Methodenrümpfe der Klasse "Konto" nicht definiert wurden.

**Comment by ekupris** [comment]
Ist abgesegnet ;)

**Comment by suglio** [comment]
Sieht gut aus!
