### ISSUE TITLE
Aufgabe 5

### ISSUE THREAD

**Issue by eulersexception** [sweIhm-ws2018-19/skillproject-di-1#2]
Zeichne zu Klassendiagramm aus Aufgabe 4 für folgenden Sachverhalt ein
Objektdiagramm

**Comment by ekupris** [comment]
Bitte um Review

**Comment by ekupris** [comment]
> Bitte um Review

@eulersexception und @suglio

**Comment by eulersexception** [comment]
Grünes Licht von meiner Seite.

**Comment by suglio** [comment]
Passt auch meinerseits!
